### ISSUE TITLE
Device backlight remains on in sleep mode 

### ISSUE THREAD

**Issue by jerbmega** [ia-me176c/device-asus-K013#31]
Sorry if this is already a known issue/part of the optimizations mentioned in #17; I submitted this issue because it wasn't explicitly mentioned in the other open issues.

When the tablet enters sleep mode, the backlight itself remains illuminated, but on the lowest brightness. This would explain why screen-on time is close to the stock ROM but the battery drain on idle is worse than stock.

**Comment by lambdadroid** [comment]
I did indeed have this problem originally, and after hours of searching for the cause I finally fixed it in https://github.com/me176c-dev/device_asus_me176c/commit/0018de7d1da532761c9aae92732fdf424400bc01

However, I recently changed some things and since then the code is failing (hooray!) so it's happening again.... I'll get this fixed ASAP.

**Comment by lambdadroid** [comment]
This log shows what's wrong:

```
08-11 09:54:30.221   217   217 I hwcomposer: Changing display state: 0
08-11 09:54:30.221   217   217 E hwcomposer: Failed to commit display state update: -13
08-11 09:54:30.221   217   217 E hwcomposer: Failed to change display state: -13
```

`-13` means `Permission denied`

**Comment by lambdadroid** [comment]
You might win one or two hours with this fix, but the root cause for the battery drain is that the tablet stays awake the whole time (there is no suspend, all it does it turn off the display). I'm attempting to get suspend working but currently it just crashes. (That's why it is disabled on all the builds I released)
