### ISSUE TITLE
Status of LineageOS 17.1

### ISSUE THREAD

**Issue by boogerlad** [ia-me176c/device-asus-K013#70]
Hi, I noticed there's a branch for this with several commits. What's the status? Will work continue, or is this abandoned? Thanks for all the great work so far!

**Comment by stephan-gh** [comment]
> Hi, I noticed there's a branch for this with several commits. What's the status?

I think I was stuck debugging some early boot crash/loop. Quite frustrating.

> Will work continue, or is this abandoned?

I don't know exactly but at the moment I have no immediate plans to continue working on it. Android requires an incredible amount of work just to deal with all the changes made for every Android version, and usually it's work that must be duplicated for each and every device. This port (and also device) is particularly special, so there are not even other device ports to copy all the needed changes from.

I've also kind of moved my focus to lower layers, i.e. mostly work on the Linux kernel at this point. I'm still willing to maintain that, i.e. make newer Linux kernel versions work for the asus-me176c. But at least at the moment I don't want to invest all the time needed to make newer Android versions work.

What this means, effectively, is that I will only keep maintaining the [asus-me176c port for postmarketOS](https://wiki.postmarketos.org/wiki/ASUS_MeMO_Pad_7_(asus-me176c)). Not because that's really better usable than Android, but more because it's just infinitely easier to maintain for me. I literally just upgrade the kernel there and everything important works and stays up to date.

I like the LineageOS port for the me176c and still use it myself sometimes, but when I think of all the work required to make new Android versions work I just can't motivate myself to work on it. Sorry :/

**Comment by boogerlad** [comment]
No need to be sorry at all :) I've tried postmarketOS and unfortunately, its usability is not comparable to Android's at the moment. It's very unresponsive, frequently hard locks, and is riddled with bugs.

How much effort is required to update LineageOS 16 with a new kernel + mesa then? Personally, I don't feel much of a difference with new Android versions anyways =P

I understand you're doing this on your own time and if you're not personally motivated, it can be difficult to do, so please don't feel pressured :)

**Comment by stephan-gh** [comment]
> No need to be sorry at all :) I've tried postmarketOS and unfortunately, its usability is not comparable to Android's at the moment. It's very unresponsive, frequently hard locks, and is riddled with bugs.

FWIW, my me176c also likes to reboot randomly on LineageOS, I don't know why that happens. Quite strange.

> How much effort is required to update LineageOS 16 with a new kernel + mesa then? Personally, I don't feel much of a difference with new Android versions anyways =P

I would expect this to be easier but it's hard to say for sure. First question is if latest Mesa still builds on LineageOS 16. The second question is which kernel to use:

- We could update to `4.19.193` (just security fixes or bugs). However, in the past staying on LTS kernel too long actually made them less reliable at some point. I tried this with `4.9` at some point, but ran into a lot of trouble when all the Meltdown stuff started happening. Had to move to `4.14` to get things somewhat stable again.
- We could update to `5.4` (used in postmarketOS) or even `5.10`. I would expect this to break at least parts of the SELinux setup though, and potentially several other compatibility problems with the old Android. Usually this is not the Linux kernel itself, but Android changing the set of patches on top of it.

My point is: updating might make it more secure, might fix some things but will certainly also break some other things. And those things usually consume a lot of time.

**Comment by boogerlad** [comment]
I'd be interested in a build with 5.10. I wonder if the latest Mesa will make animations and such more smooth, or is it the Meltdown / Spectre fixes causing the slowdown compared to the stock ROM? How much is your time worth? Would you accept a donation in Monero?

**Comment by stephan-gh** [comment]
> I wonder if the latest Mesa will make animations and such more smooth

I doubt it, this is fairly old hardware and the Mesa driver for it is pretty much obsolete. Only newer hardware generations get all the major improvements.

> or is it the Meltdown / Spectre fixes causing the slowdown compared to the stock ROM?

Not sure, but I think it's more like a general lack of optimization for this particular hardware.

> How much is your time worth? Would you accept a donation in Monero?

Not sure I'm willing to go through all the frustration to make that work even for money to be honest. It could end up being a lot of work with little benefit.

**Comment by boogerlad** [comment]
Understood, thanks for the pleasant conversation :)

**Comment by stephan-gh** [comment]
I will think about trying to provide some experimental build, to see if it maybe is possible without too much work. But I kind of expect some trouble, so don't expect it to be fully equivalent to the last release.

**Comment by stephan-gh** [comment]
> > I wonder if the latest Mesa will make animations and such more smooth
>
> I doubt it, this is fairly old hardware and the Mesa driver for it is pretty much obsolete. Only newer hardware generations get all the major improvements.

Well, it looks like I need to take that statement back :P

- https://www.phoronix.com/scan.php?page=article&item=intel-haswell-crocus&num=1
- https://www.phoronix.com/scan.php?page=news_item&px=Crocus-Has-Landed

I think this should eventually also work for this tablet. Probably not gonna make a massive difference but maybe some minor improvements.
